import { Metadata } from "next";
import { Button, styled } from "@mui/material";

export const metadata: Metadata = {
  title: "Users page",
  description: "Generated by create next app",
};

export default function UsersPage() {
  return (
    <div>
      {/* @ts-ignore */}
      <Button sx={{ mx: 1 }} variant="contained">
        Hellow Mui
      </Button>
      {/* <StyledDiv>123</StyledDiv> */}
      <h2>This is the User Index page</h2>;
    </div>
  );
}
