import { Metadata } from "next";
import { Button } from "@mui/material";
import NavigateButton from "@/app/components/tools/NavigateButton";
import CounterControl from "../components/counter/CounterControl";

export const metadata: Metadata = {
  title: "Users page",
  description: "Generated by create next app",
};

export default function UsersPage() {
  return (
    <div>
      <CounterControl />
      <Button sx={{ mx: 1 }} variant="contained">
        Hellow Mui
      </Button>
      <NavigateButton destination="/" variant="contained" sx={{ mx: 2 }}>
        back
      </NavigateButton>
      <h2>This is the User Index page</h2>
    </div>
  );
}
