import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import './globals.css'
import { ThemeProvider, createTheme } from "@mui/material";
import ThemeRegistry from "@/components/themeRegistry/ThemeRegistry";
import HeaderBar from "@/components/layout/HeaderBar";

const inter = Inter({ subsets: ["latin"] });

// const theme = createTheme({ palette: { primary: { main: "F6f51b5" } } });

export const metadata: Metadata = {
  title: "Create Next App11",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* @ts-ignore */}
        <ThemeRegistry>
          <HeaderBar />
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
