import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App11",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>This is common header</header>
        {children}
      </body>
    </html>
  );
}
