import { Box } from "@mui/material";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Index page",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <Box>
      <h1>this is page.tsx</h1>
      <Link href="/users">Users</Link>
    </Box>
  );
}
